---

version: "3.8"

services:
  all-in-one:
    build: .
    container_name: photoneo-all-in-one
    ports:
      - "8080:8080"   # Tomcat / Guacamole web
      - "4822:4822"   # guacd
      - "5432:5432"   # PostgreSQL
      - "5901:5901"   # vnc
      - "6901:6901"   # NoVNC
      - "5000:5000"   # Flask REST API
    privileged: true
    shm_size: "2g"
    volumes:
      - /home/endre/docker_mount/:/root/Desktop
    extra_hosts:
      - "host.docker.internal:host-gateway"