[package]
name = "localization_interface_redis"
version = "0.1.0"
authors = ["Endre Erős <endre.eros@chalmersindustriteknik.se>"]
edition = "2021"
autotests = false

[dependencies]
log = "0.4.22"
futures = "0.3.30"
nanoid = "0.4.0"
nalgebra = "0.33.2"
ordered-float = {version = "3.4.0", features = ["serde"] }
redis = { version = "0.29.1", features = ["tokio-comp"] }
tokio = { version = "1.36.0", features = ["full"] }
micro_sp = {git = "https://github.com/endre90/micro_sp", branch = "master"}
serde_json = "1.0.91"
serde = { version = "1.0.209", features = ["derive"] }